org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8

mod_id=gpom
mod_name=General Purpose Optimization Mod
mod_version=1.0.3
root_package=com.l.gpom

minecraft_username=Developer
extra_jvm_args=
jbr_home=
enable_foundation_debug=false
is_coremod=true
coremod_plugin_class_name=com.l.gpom.core.GPOMLoadingPlugin
